### ISSUE TITLE
Merge environment app.coffee into default app.coffee

### ISSUE THREAD

**Issue by joshrowley** [jescalan/roots#611]
Currently when using roots' environments feature, there is often duplication between the `app.coffee` and `app.production.coffee` file (or whatever environment you might be using). Local functions need to be duplicated across all files and extensions have to be loaded and configured in every single app.coffee file, even if for some of the extensions their config may not change across environments.

One way to handle this is to require your default `app.coffee` file and then modify the exported `app` object. This gets a bit clunky, especially when removing and re-adding extensions to the object.

I'd like roots to by default load the default `app.coffee` file and then override that main config with whatever differences exist in the environment specific `app.coffee`. That means only config that's different would need to be specified in environment app.coffee files. The tricky case is handling extensions, which are executed functions so we can't go back and change the config options being passed into the function. In the case of extensions, I think we should just replace the entire extension if it's configured in the environment's `extensions` array. This means that for extensions, you might need to duplicate some config values, but at least you won't need to require in and pass in every extension you use again.

I'm happy to work on a PR for this and hope to have something this week.

**Comment by jenius** [comment]
Yup this sounds good. Would love to have it merged before next week!

**Comment by SevereOverfl0w** [comment]
This would be a great feature, any progress?

**Comment by jenius** [comment]
I think we actually have this supported now, right @joshrowley?

**Comment by joshrowley** [comment]
I have a PR open for it! https://github.com/jenius/roots/pull/625

It's been a while so the code isn't fresh in my mind. There were a couple last things you wanted me to do with it. I'll take a peek at it this weekend and figure out the remaining steps left so it's ready for a merge.

**Comment by dbox** [comment]
Great idea @joshrowley
