### ISSUE TITLE
After creating new project it freezes in the console 

### ISSUE THREAD

**Issue by cassmtnr** [jescalan/roots#698]
After I create a "roots new project-name" and it is done installing packages it just freezes on "done". Is it to be like this?

![screenshot_1](https://cloud.githubusercontent.com/assets/12648633/12324320/ef500412-baa8-11e5-9b7b-acdce405d7d6.png)

**Comment by jenius** [comment]
It definitely should not. Can you control-c out of it and everything works ok?

**Comment by cassianomon** [comment]
Yes, if I ctrl-c it gets alright

**Comment by jenius** [comment]
Hmm... this is strange, but I don't honestly have the capacity to debug further at this time. Hopefully another contributor can take a look, or if you dig a little deeper and can find out any more details I might be able to fix it!
