### ISSUE TITLE
Installation not working on Mac OSX

### ISSUE THREAD

**Issue by cassianomon** [jescalan/roots#725]
I made an static page using Roots and now after some months I need to give maintenance to it and tried to reinstall Roots, somehow it's not installing in the macOS that I'm using now.

Ther error when I am trying to install:

/usr/local/lib/node_modules/roots/node_modules/mkdirp/index.js:90
                    throw err0;
                    ^

Error: EACCES: permission denied, mkdir '/Users/cassianomon/.config/roots'
  at Error (native)
  at Object.fs.mkdirSync (fs.js:794:18)
  at Function.sync (/usr/local/lib/node_modules/roots/node_modules/mkdirp/index.js:71:13)
  at Object.<anonymous> (/usr/local/lib/node_modules/roots/post_install.js:19:8)
  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (module.js:343:32)
  at Function.Module._load (module.js:300:12)
  at Function.Module.runMain (module.js:441:10)
  at startup (node.js:139:18)
  at node.js:974:3

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "roots"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE

npm ERR! roots@5.0.0 postinstall: `node ./post_install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the roots@5.0.0 postinstall script 'node ./post_install.js'.
npm ERR! This is most likely a problem with the roots package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./post_install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs roots
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls roots
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/cassianomon/.config/npm-debug.log

**Comment by jescalan** [comment]
http://roots.cx/docs/error#eacces-permission-denied

**Comment by cassianomon** [comment]
Oh, I am sorry Jeff, you can tag this as spam, I am gonna edit the Issue

**Comment by jescalan** [comment]
@cassianomon haha it's totally fine! you don't need to delete it, someone else might have the same problem in the future and find this, never know!

**Comment by drbe4t** [comment]
ya'll are awesome! Thanks for the help

**Comment by drbe4t** [comment]
Another quick question. I'm just trying to mess around with roots and I got this in one of my watch information. 
Transformers.markdown is deprecated, you must replace the :markdown jade filter, with :marked and install jstransformer-marked before you update to jade@2.0.0.
is jstransformer-marked not installed by default?

**Comment by jescalan** [comment]
@drbe4t You can check the `package.json` file under `dependencies` to find out!

**Comment by bretonio** [comment]
@jescalan your link to the Roots site is dead at the moment. We soldier on.

**Comment by jescalan** [comment]
Hi @bretonio! Sorry - roots is no longer under active maintenance, and the domain is more than $100 annually for me out of pocket, so I let it go. You can access the docs at http://roots.netlify.com/

**Comment by cassianomon** [comment]
@bretonio Check out https://github.com/static-dev/spike
