### ISSUE TITLE
Roots error when installing globally 

### ISSUE THREAD

**Issue by drbe4t** [jescalan/roots#726]
Soo i'm not quite sure what's going on. firs it gives me this. 

npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
\

then it says 

Error: EACCES: permission denied, mkdir '/Users/dannyrubio/.config/roots'
  at Error (native)
  at Object.fs.mkdirSync (fs.js:794:18)
  at Function.sync (/usr/local/lib/node_modules/roots/node_modules/mkdirp/index.js:71:13)
  at Object.<anonymous> (/usr/local/lib/node_modules/roots/post_install.js:19:8)
  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (module.js:343:32)
  at Function.Module._load (module.js:300:12)
  at Function.Module.runMain (module.js:441:10)
  at startup (node.js:139:18)
  at node.js:974:3

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "roots" "-g"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE

npm ERR! roots@5.0.0 postinstall: `node ./post_install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the roots@5.0.0 postinstall script 'node ./post_install.js'.
npm ERR! This is most likely a problem with the roots package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./post_install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs roots
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls roots
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dannyrubio/npm-debug.log

**Comment by cassianomon** [comment]
I had the same error on Mac and also on Linux, try this, it worked for me:

`npm config set prefix '~/.npm-packages'`

and adding $HOME/.npm-packages/bin to $PATH

`export PATH="$PATH:$HOME/.npm-packages/bin"`

**Comment by cassianomon** [comment]
Also check this: https://github.com/jescalan/roots/issues/725

**Comment by jescalan** [comment]
Yep #725 has the answer!
