### ISSUE TITLE
Roots won't install

### ISSUE THREAD

**Issue by uxdiva** [jescalan/roots#764]
I have a fresh install of NodeJS -- just downloaded this week. But I can't get Roots to install.
On Glitter -- someone suggested running a change owner `sudo chown -R $USER /usr/local/lib` -- Which I did, but that did not fix the problem. I would really like to use this tool, please help.

Here is the error I get. (I've attached the log at the end)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "roots" "-g"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! roots@5.1.0 postinstall: `node ./post_install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the roots@5.1.0 postinstall script 'node ./post_install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the roots package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./post_install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs roots
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls roots
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/diva/Sites/eightpix/npm-debug.log
[npm-debug.txt](https://github.com/jescalan/roots/files/785029/npm-debug.txt)

**Comment by jescalan** [comment]
Check here! https://github.com/jescalan/roots/issues/726
